# .pages.yml — Pages CMS config
# Images live in src/images/{assets,blobs,blog,brands,changelog,customers,integrations,team}

media:
  name: images
  label: Images
  input: src/images
  output: src/images
  path: ""                      # start at /src/images
  extensions: [png, jpg, jpeg, webp, svg]

settings:
  content:
    merge: true

content:
  # ---------------------
  # TEAM
  # ---------------------
  - name: team
    label: Team
    type: collection
    path: src/content/team
    filename: "{primary}.md"
    view:
      primary: name
      fields: [name, role]
      sort: [name]
    fields:
      - { name: name,  label: Name, type: string, required: true }
      - { name: role,  label: Role, type: string }
      - { name: bio,   label: Bio,  type: text }
      - name: image
        label: Image
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images, path: team } }   # src/images/team
          - { name: alt, label: Alt text, type: string }
      - name: socials
        label: Socials
        type: object
        fields:
          - { name: twitter,  label: Twitter,  type: string }
          - { name: website,  label: Website,  type: string }
          - { name: linkedin, label: LinkedIn, type: string }
          - { name: email,    label: Email,    type: string }
      - { name: body, label: Body, type: rich-text }

  # ---------------------
  # CUSTOMERS
  # ---------------------
  - name: customers
    label: Customers
    type: collection
    path: src/content/customers
    filename: "{primary}.md"
    view:
      primary: customer
      fields: [customer]
      sort: [customer]
    fields:
      - { name: customer,   label: Customer, type: string, required: true }
      - { name: ctaTitle,   label: CTA Title, type: string }
      - { name: testimonial,label: Testimonial, type: text }
      - { name: partnership,label: Partnership, type: string }
      - name: avatar
        label: Avatar
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images, path: customers } }  # src/images/customers
          - { name: alt, label: Alt text, type: string }
      - name: challengesAndSolutions
        label: Challenges & Solutions
        type: object
        list: true
        fields:
          - { name: title,   label: Title,   type: string }
          - { name: content, label: Content, type: text }
      - name: results
        label: Results
        type: string
        list: true
      - { name: about,   label: About,   type: text }
      # 'details' is a record in your schema; model it as key/value pairs
      - name: details
        label: Details
        type: list
        fields:
          - { name: key,   label: Key,   type: string }
          - { name: value, label: Value, type: string }
      - name: logo
        label: Logo
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images, path: customers } }
          - { name: alt, label: Alt text, type: string }
      - { name: body, label: Body, type: rich-text }

  # ---------------------
  # INTEGRATIONS
  # ---------------------
  - name: integrations
    label: Integrations
    type: collection
    path: src/content/integrations
    filename: "{primary}.md"
    view:
      primary: integration
      fields: [integration, email]
      sort: [integration]
    fields:
      - { name: email,       label: Contact Email, type: string }
      - { name: integration, label: Integration,   type: string, required: true }
      - { name: description, label: Description,   type: text }
      - name: permissions
        label: Permissions
        type: string
        list: true
      - name: details
        label: Details
        type: list
        fields:
          - { name: title, label: Title, type: string }
          - { name: value, label: Value, type: string }
          - { name: url,   label: URL,   type: string }
      - name: logo
        label: Logo
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images, path: integrations } } # src/images/integrations
          - { name: alt, label: Alt text, type: string }
      - { name: tags, label: Tags, type: string, list: true }

  # ---------------------
  # CHANGELOG
  # ---------------------
  - name: changelog
    label: Changelog
    type: collection
    path: src/content/changelog
    filename: "{primary}.md"
    view:
      primary: page
      fields: [page, pubDate]
      sort: [pubDate]
      default: { sort: pubDate, order: desc }
    fields:
      - { name: page,        label: Page,        type: string, required: true }
      - { name: description, label: Description, type: text }
      - { name: pubDate,     label: Publication Date, type: date }
      - name: image
        label: Image
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images, path: changelog } } # src/images/changelog
          - { name: alt, label: Alt text, type: string }
      - { name: body, label: Body, type: rich-text }

  # ---------------------
  # POSTS
  # ---------------------
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    filename: "{year}{month}{day}-{hour}{minute}{second}.md"
    view:
      primary: title
      fields: [title, pubDate, team]
      sort: [pubDate]
      default: { sort: pubDate, order: desc }
    fields:
      - { name: title,       label: Title, type: string, required: true }
      - { name: pubDate,     label: Publication Date, type: date }
      - { name: description, label: Description, type: text }
      - { name: team,        label: Team, type: string }
      - name: image
        label: Cover Image
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images, path: blog } }   # src/images/blog
          - { name: alt, label: Alt text, type: string }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }

  # ---------------------
  # HELP CENTER
  # ---------------------
  - name: helpcenter
    label: Help Center
    type: collection
    path: src/content/helpcenter
    filename: "{primary}.md"
    view:
      primary: page
      fields: [page]
      sort: [page]
    fields:
      - { name: page,        label: Page,        type: string, required: true }
      - { name: description, label: Description, type: text }
      - { name: category,    label: Category,    type: string }
      - name: keywords
        label: Keywords
        type: string
        list: true
      - { name: lastUpdated, label: Last Updated, type: string }
      - name: faq
        label: FAQ
        type: list
        fields:
          - { name: question, label: Question, type: string }
          - { name: answer,   label: Answer,   type: text }
      - { name: body, label: Body, type: rich-text }

  # ---------------------
  # INFO PAGES
  # ---------------------
  - name: infopages
    label: Info Pages
    type: collection
    path: src/content/infopages
    filename: "{primary}.md"
    view:
      primary: page
      fields: [page, pubDate]
      sort: [page]
    fields:
      - { name: page,    label: Page, type: string, required: true }
      - { name: pubDate, label: Publication Date, type: date }
      - { name: body,    label: Body, type: rich-text }
